version: '3.8'

services:
  libapp:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: libapp
    depends_on:
      - database
    environment:
      - POSTGRES_USER=jubydull
      - POSTGRES_PASSWORD=juby1234
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/library
      - SPRING_DATASOURCE_USERNAME=jubydull
      - SPRING_DATASOURCE_PASSWORD=juby1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update


    ports:
      - "6868:8080"

  database:
    image: postgres
    container_name: database
    environment:
      - POSTGRES_USER=jubydull
      - POSTGRES_PASSWORD=juby1234
      - POSTGRES_DB=library
    ports:
      - "5433:5432"